version: '3'
services:
  app:
    build: .  # Build context is the root of the project for the app

  db:
    build:
      context: ./db  # Points to the db folder, where the Dockerfile is located
    volumes:
      - ./db/world.sql:/docker-entrypoint-initdb.d/world.sql  # Map the SQL file for initialization
    command: --default-authentication-plugin=mysql_native_password
    restart: always
