version: '3'
services:
  app:
    build: .  # Build context is the root of the project for the app

  db:
    build: db/.  # Points to the db folder, where the Dockerfile is located
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
