@startuml

actor User as "Organization End-User"

rectangle Database

rectangle "Population Reporting System" {
    usecase UC2 as "Generate City Report"

    usecase UC2a as "Filter by Continent, Country, or District"

    User - UC2
    UC2 ..> UC2a : include
    UC2 - Database
}

@enduml
l